liveblog/liveblog

client/app/scripts/liveblog-edit/styles/liveblog-edit.less
client/app/scripts/liveblog-edit/timeline.js
client/app/scripts/liveblog-edit/views/timeline-item-remove.html
client/app/scripts/liveblog-edit/views/timeline-item.html
client/app/scripts/liveblog-edit/views/timeline-post-actions.html

Item removal it's done by clicking a small 'x' sign
Posts are removable now by an action from the options drop-down

LBSD-369 Improvements to delete on timeline

---

client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/posts.service.js
client/app/scripts/liveblog-edit/timeline.js
client/tasks/options/requirejs.js

And repair the build grunt task

Timeline: refactored and uses PostService

---

client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/views/main.html
client/spec/editor_draft_posts_spec.js

Ask a confirmation before overwriting the editor

---

client/app/scripts/liveblog-edit/directives.js
client/app/scripts/liveblog-edit/styles/post.less
client/app/scripts/liveblog-edit/views/post.html
client/spec/editor_draft_posts_spec.js

no more action to remove an item in a post and no more dropdown for them but a tooltip
LBSD-413

Post actions simplified

---

client/app/scripts/liveblog-edit/styles/draft-posts.less
client/app/scripts/ng-sir-trevor-blocks.js

Fix/Embed code: let the embed block to give the illustration size

---

client/spec/timeline_add_edit_spec.js

https://bamboo.sourcefabric.org/chain/result/viewChainResult.action?planKey=LBSD-DBRT&buildNumber=22#new-failed-tests maybe fixed.

timeline e2e test: wait for the update before checking the value of the text

---

client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/views/settings.html
client/spec/blog_settings_spec.js

Show image, full name and username

LBSD-88 Show original creator in blog settings

---

client/bower.json
server/requirements.txt

updated: https://github.com/superdesk/superdesk/pull/507

SD udpdated to fix a link issue

---

server/apps/prepopulate/test.json

fix: id_name same name changed.

---

client/app/index.html
client/app/scripts/main.js
client/app/styles/less/liveblog.less
client/app/styles/less/variables.less
client/bower.json
client/tasks/options/cssmin.js
client/tasks/options/less.js
client/tasks/options/template.js
client/tasks/options/usemin.js
client/tasks/options/useminPrepare.js

- `superdesk-desks` added to modules

Users management fixed and styles from SD generated by grunt (LBSD-498)

---

client/bower.json

Hope it will work... Because I can't test emails locally.  :weary:
Related to https://github.com/superdesk/superdesk/pull/742

SD updated to fix an issue with the reset password feature [LBSD-528]

---

client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/styles/settings.less
client/app/scripts/liveblog-edit/views/settings.html
client/spec/blog_settings_spec.js

Besides the edit blog team feature, the change blog owner button changed
allong the the modal to do so

LBSD-526 Edit blog team via settings plus other UI changes

---

client/app/scripts/liveblog-bloglist/module.js
client/spec/blogs_list_spec.js

The blogs list is now available with 3 urls:
- `/liveblog/`, shows all the activated blogs
- `/liveblog/active`, alias for `/liveblog/`
- `/liveblog/archived`, shows all the archived blogs

Feature/deep linking blog list [LBSD-456]

---

client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/styles/post.less

Changed updated time font size from pt to px
Closing( if open) the owner dropdown when editing the blog team

LBSD-556 Minor ui-ux fixes

---

server/liveblog/embed/embed_assets/themes/angular-base/liveblog-embed/pages-manager.service.js
server/liveblog/embed/embed_assets/themes/angular-base/liveblog-embed/permalink.service.js
server/liveblog/embed/embed_assets/themes/angular-base/theme.json
server/liveblog/embed/embed_assets/themes/default-theme/main.js
server/liveblog/embed/embed_assets/themes/default-theme/styles/embed.css
server/liveblog/embed/embed_assets/themes/default-theme/template.html
server/liveblog/embed/embed_assets/themes/default-theme/theme.json

feature: permalink initial draft.

---

client/app/scripts/liveblog-edit/styles/post.less
client/app/scripts/liveblog-edit/styles/timeline.less
client/app/scripts/liveblog-edit/views/post.html

and Make images max width to 100% - timeline and drafts panel [LBSD-609]

Add 15px between posts in timeline [LBSD-610]

---

client/app/scripts/ng-sir-trevor-blocks.js

Remove a duplicated id for file upload

Feature/allow to add two images in a post [LBSD-614]

---

client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/views/main.html

Disable submit button when publishing or saving as drafts and the other
way around

LBSD-637 Disable submit button when action is pending

---

client/app/scripts/liveblog-edit/module.js
client/spec/blog_settings_spec.js

Administrator should be able to edit blog settings even if not blog owner

LBSD-627 Administrator should be able to edit blog settings

---

client/app/scripts/ng-sir-trevor-blocks.js

fix: replace facebook embed code by permalink.

---

server/superdesk/templates/account_created.html
server/superdesk/templates/account_created.txt
server/superdesk/templates/invited_members.html
server/superdesk/templates/invited_members.txt
server/superdesk/templates/reset_password.html
server/superdesk/templates/reset_password.txt
server/superdesk/templates/reset_password_subject.txt

… by removing unnecessary Sourcefabric corporate data and simplifying a few sentences.
LBSD-667

Updates the email notification messages

---

client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/views/main.html
client/app/scripts/ng-sir-trevor-blocks.js
client/spec/helpers/pages.js
client/spec/timeline_add_edit_spec.js

fix: disable publish button if empty.

---

client/app/styles/less/liveblog.less

Acceptance criteria:
hide “Preferences”, “Privileges”, and “Activity Stream” from users
profile page: http://liveblogdevel.dev.superdesk.org/#/profile/

LBSD-671 Clean up blog UI

---

client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/views/main.html

fix: added disable for save draft and submit.

---

client/app/scripts/liveblog-edit/blog.service.js
client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/styles/timeline.less
client/app/scripts/liveblog-edit/views/main.html

feature: added link to the live blog output

---

client/app/scripts/liveblog-edit/directives.js
client/app/scripts/liveblog-edit/styles/post.less
client/app/scripts/liveblog-edit/views/post.html
client/spec/helpers/pages.js
client/spec/timeline_spec.js
server/apps/prepopulate/test.json

feature: disable reorder for single post on a blog.

---

client/app/scripts/liveblog-edit/directives.js
client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/styles/posts-in-panel.less
client/app/scripts/liveblog-edit/unread.posts.service.js
client/app/scripts/liveblog-edit/views/main.html
client/app/scripts/liveblog-edit/views/post.html
client/spec/editor_contribution_posts_spec.js
client/spec/helpers/pages.js
server/liveblog/posts/posts.py

feature: highlithing the new posts in the list of contributions.

---

server/liveblog/blogs/blogs.py

Reverts superdesk/liveblog#247

Revert "LBSD-701 added email notification for blog members"

---

client/spec/editor_contribution_posts_spec.js
server/liveblog/themes/themes_assets/angular/liveblog-embed/directives.js
server/liveblog/themes/themes_assets/classic/styles/embed.css
server/liveblog/themes/themes_assets/classic/template.html

New directive LbFluidIframe added to lb-theme-angular which save the aspect ratio of the orignal iframe, set the full width and preserve the original ratio.

lbFluidIframe directive added to angluar-theme and used in classic-theme

---

server/liveblog/blogs/blogs.py

Still need to filter the email receivers to let only new members to receive membership email

  LBSD-701 added email notification for blog members

---

server/liveblog/themes/themes.py

Wrong property name for `blog_preferences.theme`

Fix removing a theme LBSD-711

---

client/app/scripts/liveblog-edit/module.js
client/app/scripts/ng-sir-trevor-blocks.js
server/settings.py

feature: use setsrc to support multiple images depending on resolution.

---

client/app/scripts/liveblog-edit/views/main.html
client/app/scripts/liveblog-security.service.js

Editors should be able to edit/remove/publish posts by any contributor
regardless of their role (i.e. from contributors, other editors, and
admins).

LBSD-709 Fix inconsistency in the permission of an editor

---

client/app/scripts/liveblog-bloglist/styles/liveblog-bloglist.less

Added scrollbar in the blog list when needed

LBSD-729 Fix/scrollbar in blog list

---

client/app/scripts/liveblog-bloglist/module.js
client/app/scripts/main.js

I removed the directive that was doing that

LBSD-730 Remove ctrl+0 binding to modal dialog

---

server/liveblog/themes/themes_assets/angular/liveblog-embed/directives.js
server/liveblog/themes/themes_assets/classic/styles/embed.css
server/liveblog/themes/themes_assets/classic/template.html

custom generic embed for themes

---

server/liveblog/blogs/blogs.py
server/liveblog/posts/posts.py
server/requirements.txt

depends on https://github.com/superdesk/superdesk-core/pull/86

Store the post order sequence in database instead of redis LBSD-708

---

server/liveblog/themes/themes_assets/angular/liveblog-embed/resources.service.js
server/liveblog/themes/themes_assets/classic/main.js
server/liveblog/themes/themes_assets/classic/template.html

use srcset in embed for blog image with the settings rendition.

feature: implement image rendition for blog image in the embed.

---

server/liveblog/themes/themes_assets/angular/liveblog-embed/pages-manager.service.js

fix: remove unpublished posts

---

README.md

and remove duplicate reference

Link to merged Dockerfile in the README

---

server/liveblog/themes/themes_assets/angular/liveblog-embed/resources.service.js
server/liveblog/themes/themes_assets/classic/main.js

As an editor, I want all changes to the blog settings (blog title,
description, image) to be auto-updated in the embed without need to
refresh the page (embed) manually.

LBSD-774 autoupdate blog settings

---

server/apps/prepopulate/data_initialization/roles.json

fix: disallow editors to access `Users Management`

---

server/liveblog/themes/themes_assets/classic/styles/embed.css

the sticky drawer button was on top of the comments panel

LBSD-821 small css fix

---

client/app/scripts/main.js

fix: show error only when loged in (session exists).

---

client/app/scripts/liveblog-edit/posts.service.js
client/app/scripts/liveblog-edit/views/post.html
server/liveblog/posts/posts.py
server/liveblog/themes/themes_assets/angular/liveblog-embed/resources.service.js
server/liveblog/themes/themes_assets/classic/views/posts.html

to track changes in content for a post.
Conflicts:
server/liveblog/themes/themes_assets/classic/template.html

feature: added `content_updated_date` property.

---

server/liveblog/blogs/blogs.py
server/liveblog/embed/__init__.py
server/liveblog/embed/embed.py

feature: remove blog from media.

---

client/app/index.html

fix: remove unexisting css.

---

server/requirements.txt

revert last sd-core changes #393

revert: s3 timestamp update

---

client/app/scripts/liveblog-bloglist/module.js
client/app/scripts/liveblog-bloglist/styles/liveblog-bloglist.less
client/app/scripts/liveblog-edit/views/settings.html
client/bower.json

Markup only changes are now 'savable' in blog settings

LBSD-1000 Markup in blog description

---

Dockerfile

Regarding: https://dev.sourcefabric.org/browse/LBSD-997

Update Dockerfile for update basic themes during bamboo deployment

---

.gitignore

Vim specific gitignore rules

---

README.md
Vagrantfile
scripts/vagrant-init-database.sh
scripts/vagrant-provision.sh
scripts/vagrant-start-dev.sh

Create and provision a local development environment living inside a linux container

Vagrant lxc

---

README.md

I added the full installation process inside the readme

A readme that is actually useful

---

server/features/environment.py
server/features/steps/steps_syndication.py
server/features/syndication_blogs.feature
server/liveblog/syndication/__init__.py
server/liveblog/syndication/auth.py
server/liveblog/syndication/blogs.py
server/liveblog/syndication/consumer.py
server/liveblog/syndication/producer.py
server/liveblog/tests/__init__.py
server/liveblog/tests/environment.py

- LBSD-1041: Syndication Blogs API Endpoint
- LBSD-1049: Syndication API Key Auth
- Behave tests & utilities for Consumer & API Key Auth

Syndication Blogs API Endpoint and API Key Auth (LBSD-1049, LBSD-1041)

---

server/app.py
server/features/environment.py
server/features/steps/steps_syndication.py
server/features/syndication_blogs.feature
server/features/syndication_producers.feature
server/liveblog/syndication/__init__.py
server/liveblog/syndication/auth.py
server/liveblog/syndication/blogs.py
server/liveblog/syndication/consumer.py
server/liveblog/syndication/producer.py
server/liveblog/tests/__init__.py
server/liveblog/tests/environment.py

Custom API endpoint to let Consumer admin users to get the list of available producer blogs. The request is proxied directly to Producer Blogs API using python requests.

LBSD-1083: Consumer Blogs API Endpoint

---

client/app/index.html
client/app/scripts/liveblog-syndication/directives/consumer-list.js
client/app/scripts/liveblog-syndication/directives/copy-to-clipboard.js
client/app/scripts/liveblog-syndication/views/consumer-list-item.html

Small directive that allows you to easily copy the consumer api key to the clipboard

Copy api key

---

client/app/scripts/liveblog-syndication/views/producer-list-item.html
client/spec/helpers/pages.js
client/spec/producers_spec.js
server/liveblog/prepopulate/test.json

Producers management tests

---

client/app/scripts/liveblog-syndication/views/consumer-list-item.html
client/spec/consumers_spec.js
server/liveblog/prepopulate/test.json

Shiny end-to-end testing for the consumer management endpoint

Consumers management tests

---

client/app/index.html
client/app/scripts/liveblog-syndication/controllers/base.js
client/app/scripts/liveblog-syndication/directives/consumer-edit.js
client/app/scripts/liveblog-syndication/directives/contacts-edit.js
client/app/scripts/liveblog-syndication/directives/producer-edit.js
client/app/scripts/liveblog-syndication/views/consumer-edit-form.html
client/app/scripts/liveblog-syndication/views/consumer-list-item.html
client/app/scripts/liveblog-syndication/views/consumer-list.html
client/app/scripts/liveblog-syndication/views/contacts-edit-form.html
client/app/scripts/liveblog-syndication/views/producer-edit-form.html
client/app/scripts/liveblog-syndication/views/producer-list.html
server/liveblog/syndication/producer.py

n contacts may be added to consumer and producer on the client. Contacts are persisted to the consumer whereas they weren't before

LBSD-1085 Contacts may be added to both consumers and producers

---

client/app/index.html
client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-syndication/actions/ingest-panel.js
client/app/scripts/liveblog-syndication/directives/attach-syndicated-blogs-modal.js
client/app/scripts/liveblog-syndication/directives/ingest-panel.js
client/app/scripts/liveblog-syndication/flux.js
client/app/scripts/liveblog-syndication/index.js
client/app/scripts/liveblog-syndication/reducers/ingest-panel.js
client/app/scripts/liveblog-syndication/styles/syndication.less
client/app/scripts/liveblog-syndication/views/attach-syndicated-blogs-modal.html
client/app/scripts/liveblog-syndication/views/ingest-panel.html
client/spec/helpers/pages.js

Brace yourself, it's pretty dense

Ingest panel

---

client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/posts.service.js
client/app/scripts/liveblog-syndication/actions/incoming-syndication.js
client/app/scripts/liveblog-syndication/directives/incoming-syndication.js
client/app/scripts/liveblog-syndication/directives/ingest-panel.js
client/app/scripts/liveblog-syndication/flux.js
client/app/scripts/liveblog-syndication/reducers/incoming-syndication.js
client/app/scripts/liveblog-syndication/styles/syndication.less
client/app/scripts/liveblog-syndication/views/incoming-syndication.html

Display blogs and posts in the ingest panel

Incoming syndication

---

client/app/scripts/liveblog-syndication/actions/ingest-panel.js
client/app/scripts/liveblog-syndication/views/attach-syndicated-blogs-modal.html
server/liveblog/syndication/producer.py
server/liveblog/syndication/syndication.py

Added auto_publish flag to in_syndication. Status of post is set accordingly in webhook.

Added auto_publish flag to in_syndication

---

server/features/syndication_posts.feature
server/liveblog/blogs/__init__.py
server/liveblog/blogs/blogs.py
server/liveblog/global_preferences.py
server/liveblog/posts/__init__.py
server/liveblog/syndication/__init__.py
server/liveblog/syndication/blogs.py
server/liveblog/syndication/consumer.py
server/liveblog/syndication/producer.py
server/liveblog/syndication/syndication.py
server/settings.py

- Producer blog posts API endpoint
- Fixes

LBSD-1063: Producer blog posts API endpoint

---

server/liveblog/syndication/exceptions.py
server/liveblog/syndication/syndication.py
server/liveblog/syndication/utils.py

Fetch and send producer blog posts to consumer on syndication_out post-create (WIP)

LBSD-1115: Fetch and send producer blog posts to consumer on syndication_out post-create

---

server/liveblog/syndication/exceptions.py
server/liveblog/syndication/syndication.py
server/liveblog/syndication/utils.py

Fetch and store images from producer blog posts

LBSD-1109: Fetch and store images from producer blog posts

---

client/app/scripts/liveblog-syndication/actions/ingest-panel.js
client/app/scripts/liveblog-syndication/directives/attach-syndicated-blogs-modal.js
client/app/scripts/liveblog-syndication/directives/ingest-panel.js
client/app/scripts/liveblog-syndication/reducers/ingest-panel.js
client/app/scripts/liveblog-syndication/styles/syndication.less
client/app/scripts/liveblog-syndication/views/attach-syndicated-blogs-modal.html
client/app/scripts/liveblog-syndication/views/incoming-syndication.html
client/app/scripts/liveblog-syndication/views/ingest-panel.html

* Delete a syndication
* Update auto publish value

Lbsd 1140 - Dropdown in ingest panel

---

server/liveblog/syndication/syndication.py
server/liveblog/syndication/tasks.py
server/liveblog/syndication/utils.py

- Check for duplicate posts on syndication webhook request (only for new posts)
- New formatting for producer_post_id post field

LBSD-1141: Check for duplicate posts on syndication webhook request.

---

client/app/index.html
client/app/scripts/liveblog-edit/unread.posts.service.js
client/app/scripts/liveblog-edit/views/main.html
client/app/scripts/liveblog-syndication/directives/incoming-syndication.js
client/app/scripts/liveblog-syndication/directives/notifications-count.js
server/liveblog/posts/posts.py

This covers the following:
* LBSD-1150
* LBSD-1139

LBSD 1150/1139 - Define notification origin for incoming syndicated posts + UI

---

server/liveblog/posts/posts.py
server/liveblog/syndication/consumer.py
server/liveblog/syndication/syndication.py
server/liveblog/syndication/tasks.py

Support for updating syndicated blog posts data using webhook (wip)

LBSD-1117: Syndication webhook: update posts

---

server/requirements.txt

related PR:
* https://github.com/liveblog/superdesk-core/pull/14

chore: update superdesk-core with fix notification issue.

---

server/liveblog/syndication/syndication.py
server/liveblog/syndication/utils.py

- Push only locally produced posts.
- Bugfix for duplicate content check.

LBSD-1177: Push only locally produced posts

---

server/liveblog/blogs/blogs.py
server/liveblog/syndication/syndication.py

Delete in & out syndication on blog delete

LBSD-1156: Delete in & out syndication on blog delete

---

client/app/scripts/liveblog-syndication/actions/ingest-panel.js
client/app/scripts/liveblog-syndication/directives/attach-syndicated-blogs-modal.js
client/app/scripts/liveblog-syndication/directives/ingest-panel.js
client/app/scripts/liveblog-syndication/reducers/ingest-panel.js
client/app/scripts/liveblog-syndication/views/consumer-edit-form.html
client/spec/consumers_spec.js
server/features/steps/steps_syndication.py
server/features/syndication_blogs.feature
server/liveblog/syndication/blogs.py
server/liveblog/syndication/producer.py
server/liveblog/syndication/syndication.py
server/liveblog/syndication/tasks.py
server/liveblog/syndication/utils.py
server/liveblog/tests/__init__.py

- Added _start_date_ to _syndication_in_ & _syndication_out_ schema.
- Added PATCH support to _blogs_ and _syndication_ blueprints.
- Added behave test for _blogs_ syndicate blueprint.

LBSD-1151: Allow consumer to have syndicated posts from a specific date

---

client/app/scripts/liveblog-syndication/directives/consumer-edit.js
client/app/scripts/liveblog-syndication/views/consumer-edit-form.html
client/app/scripts/liveblog-syndication/views/consumer-list-item.html
client/app/scripts/liveblog-syndication/views/consumer-list.html
client/spec/consumers_spec.js
server/features/syndication_consumers.feature
server/features/syndication_producers.feature
server/liveblog/syndication/__init__.py
server/liveblog/syndication/consumer.py
server/liveblog/syndication/producer.py
server/liveblog/syndication/syndication.py
server/liveblog/syndication/utils.py
server/liveblog/syndication/validation.py
server/liveblog/syndication/validators.py

- Change api_url to webhook_url on both backend and client app
- Updated behave tests and specs
- Fix for consumer list markup issue (username classname had different width)
- Updated httpsurl validator

LBSD-1175: Change api_url to webhook_url

---

server/features/syndication_consumers.feature
server/features/syndication_producers.feature
server/liveblog/syndication/__init__.py
server/liveblog/syndication/consumer.py
server/liveblog/syndication/producer.py
server/liveblog/syndication/syndication.py
server/liveblog/syndication/utils.py
server/liveblog/syndication/validation.py
server/liveblog/syndication/validators.py

- Force HTTPS for syndication Syndication API urls
- Check token based authentication (optional)

LBSD-1119: SyndicationValidator for secure urls and auth tokens

---

server/features/syndication_blogs.feature
server/liveblog/blogs/blogs.py
server/liveblog/tests/environment.py
server/liveblog/tests/test_settings.py

- Disable switch off of syndication_enabled if blog has consumers.
- Disable delete of blog if blog has consumers.
- Fix for behave tests for DATE_FORMAT validation.

LBSD-1176: Disable switch off of syndication_enabled if blog has consumers.

---

client/app/scripts/liveblog-marketplace/controllers/marketer.js
client/app/scripts/liveblog-marketplace/views/marketer.html

This is a WIP, pargination for marketers is not yet working

LBSD-1227 Pagination for marketplace

---

client/tasks/options/template.js
server/features/syndication_consumers.feature
server/features/syndication_producers.feature
server/liveblog/syndication/consumer.py
server/liveblog/syndication/producer.py
server/liveblog/syndication/validation.py

- Fix unique validation for webhook_url and api_url
- Bugfix for token auth validation
- Behave tests to check unique url validation for api_url and webhook_url.

LBSD-1241: Prevent creation of consumer and producer with same webhook or api url

---

client/app/scripts/liveblog-bloglist/module.js
client/app/scripts/liveblog-edit/views/freetype-image.html

sd-plain-image support for minimum sizes.
ads-local upload image minimum size set to 200x200

fix: minimum size for ads-local image set to 200x200.

---

client/app/scripts/liveblog-edit/controllers/blog-edit.js

Reset post type to default when saving, updating submitting and
publishing

LBSD-1245 Reset post type to default

---

client/app/scripts/liveblog-edit/posts.service.js
client/app/scripts/liveblog-syndication/directives/consumer-edit.js
client/app/scripts/liveblog-syndication/directives/ingest-panel.js
client/app/scripts/liveblog-syndication/directives/producer-edit.js
client/app/scripts/liveblog-syndication/views/consumer-edit-form.html
client/app/scripts/liveblog-syndication/views/producer-edit-form.html
client/app/scripts/liveblog-syndication/views/producer-list.html
client/spec/consumers_spec.js
client/spec/producers_spec.js
docker/Procfile-dev
server/liveblog/syndication/auth.py
server/liveblog/syndication/blogs.py
server/liveblog/syndication/consumer.py
server/liveblog/syndication/producer.py
server/liveblog/syndication/syndication.py
server/liveblog/syndication/tasks.py
server/liveblog/syndication/utils.py
server/liveblog/syndication/validation.py

- LBSD-1276: python-requests timeout while running app using default flask
- LBSD-1276: using gunicorn rest server on docker/Procfile-dev
- LBSD-1275: delete of syndication fix on client app
- LBSD-1270: Display unique error on consumer & producer edit form
- http requests fixes, error message changed.

Syndication bugfixes & cleanup

---

client/app/scripts/liveblog-edit/directives.js

the same as
https://github.com/liveblog/liveblog/pull/601

fix: keep the original size for image ads.

---

client/app/index.html
client/app/scripts/liveblog-syndication/controllers/consumers.js
client/app/scripts/liveblog-syndication/controllers/producers.js
client/app/scripts/liveblog-syndication/controllers/syndication.js
client/app/scripts/liveblog-syndication/directives/consumers.js
client/app/scripts/liveblog-syndication/directives/producers.js
client/app/scripts/liveblog-syndication/index.js
client/app/scripts/liveblog-syndication/styles/syndication.less
client/app/scripts/liveblog-syndication/views/consumer-list.html
client/app/scripts/liveblog-syndication/views/producer-list.html
client/app/scripts/liveblog-syndication/views/syndication.html
client/spec/consumers_spec.js
client/spec/helpers/pages.js

Both consumers management and producers management have been replaced by one menu called syndication.
In the syndication it is possible to switch between consumers & producers view via tabs.

Syndication menu

---

client/app/scripts/liveblog-edit/styles/liveblog-edit.less
client/app/scripts/liveblog-edit/views/main.html
client/app/scripts/liveblog-freetypes/views/list.html

LBSD-1272 Limit freetype title size

---

client/app/scripts/liveblog-edit/freetype.service.js

https://github.com/liveblog/liveblog/pull/644

fix: escape input text.

---

.travis.yml
client/app/scripts/liveblog-edit/module.js
client/bower.json
client/tasks/options/template.js

* Replaced embedly with iframely.
* Added new encoded iframely environment variable for travis.

LBSD-1340 Switched to iframely

---

client/app/scripts/liveblog-edit/controllers/blog-settings.js
server/liveblog/blogs/blogs.py

Set default value for empty start_date.

LBSD-1335: Set default value for empty start_date

---

client/app/scripts/liveblog-syndication/views/attach-syndicated-blogs-modal.html

Syndication attach new blog, there should be an error message if producer does not have any blog

LBSD-1333 Error message when no blogs found

---

.travis.yml
client/app/scripts/liveblog-edit/module.js
client/bower.json
client/tasks/options/template.js

Revert "LBSD-1340 Switched to iframely"

---

client/app/scripts/liveblog-edit/views/ads-local.html
client/app/styles/less/lb-bootstrap.less

As an editor/advertiser I want to upload smaller images to the post type
local ad and show them in the original size

LBSD-1244 upload smaller images to the post type local ad and show them in the original size

---

client/app/scripts/liveblog-freetypes/styles/freetypes.less
client/app/scripts/liveblog-freetypes/views/list.html

Create New Free Type is without information about needed mandatory
values

LBSD-1271 Add mandatory values for Free type creation

---

client/app/scripts/liveblog-bloglist/module.js
client/app/scripts/liveblog-edit/views/settings.html

fix for both blog settings and blog creation

LBSD-1441 fix blog avatar workaround for adding too small image

---

client/app/scripts/liveblog-edit/blog.service.js
client/app/scripts/liveblog-edit/index.js
client/app/scripts/liveblog-edit/pages-manager.service.js
client/app/scripts/liveblog-edit/posts.service.js
client/app/scripts/liveblog-edit/unread.posts.service.js

Refactoring the way services are being required.

Refactoring service requirement

---

client/app/scripts/liveblog-edit/directives.js
client/app/scripts/liveblog-edit/directives/autofocus.js
client/app/scripts/liveblog-edit/directives/bind-html.js
client/app/scripts/liveblog-edit/directives/filter-by-member.js
client/app/scripts/liveblog-edit/directives/freetype-collection-add.js
client/app/scripts/liveblog-edit/directives/freetype-collection-remove.js
client/app/scripts/liveblog-edit/directives/freetype-embed.js
client/app/scripts/liveblog-edit/directives/freetype-image.js
client/app/scripts/liveblog-edit/directives/freetype-link.js
client/app/scripts/liveblog-edit/directives/freetype-render.js
client/app/scripts/liveblog-edit/directives/freetype-text.js
client/app/scripts/liveblog-edit/directives/full-height.js
client/app/scripts/liveblog-edit/directives/item.js
client/app/scripts/liveblog-edit/directives/posts-list.js
client/app/scripts/liveblog-edit/directives/select-text-on-click.js
client/app/scripts/liveblog-edit/directives/stop-event.js

Moving in every directives in separate files inside the directives folder.

Refactoring edit directives

---

client/app/scripts/liveblog-syndication/actions/ingest-panel.js
client/app/scripts/liveblog-syndication/directives/attach-syndicated-blogs-modal.js
client/app/scripts/liveblog-syndication/directives/ingest-panel-dropdown.js
client/webpack.config.js

* Normalize and denormalize the date before sending it.
* Always send UTC date
* Fix invalid date in attach syndication modal and ingest panel dropdown.
* Linting

LBSD-1483 Cannot attach producer when a date is set

---

client/app/scripts/liveblog-edit/controllers/blog-edit.js
client/app/scripts/liveblog-edit/directives/posts-list.js
client/app/scripts/liveblog-edit/views/main.html
client/app/scripts/liveblog-syndication/actions/ingest-panel.js
client/app/scripts/liveblog-syndication/directives/incoming-syndication.js
client/app/scripts/liveblog-syndication/directives/ingest-panel.js
client/app/scripts/liveblog-syndication/directives/notifications-count.js
client/app/scripts/liveblog-syndication/reducers/ingest-panel.js
client/app/scripts/liveblog-syndication/styles/syndication.scss
client/app/scripts/liveblog-syndication/views/ingest-panel.html

* [LBSD-1493](https://dev.sourcefabric.org/browse/LBSD-1493): Indicate which ingest has a new incoming post 
* [LBSD-1549](https://dev.sourcefabric.org/browse/LBSD-1549): Incoming non auto-published syndicated post is appearing in the contribution panel on notification

Fixes and improvements for incoming syndication notifications

---

client/app/scripts/liveblog-syndication/controllers/base.js
client/app/scripts/liveblog-syndication/views/consumer-list.html
client/spec/consumers_spec.js
client/spec/producers_spec.js
server/liveblog/prepopulate/test.json

https://dev.sourcefabric.org/browse/LBSD-1479

Pagination for consumers & producers

---

client/bower.json

Related PR: https://github.com/liveblog/superdesk/pull/10

Deactivate the possibility for non network instance to create admin users

---

client/app/scripts/liveblog-bloglist/module.js
client/app/scripts/liveblog-bloglist/views/main.html

Limit number of access requests for a blog according to current team number & pending access requests
https://dev.sourcefabric.org/browse/LP-62

LP-62 Restrict requests to access blogs, when max number of team members has been reached already

---

client/app/index.html

https://dev.sourcefabric.org/browse/LBSD-1516

changed link to manual on live blog about page

---

README.md
Vagrantfile
client/app/scripts/liveblog-syndication/views/consumer-list-item.html
client/app/scripts/liveblog-syndication/views/producer-list-item.html
client/package.json
client/webpack.config.js
scripts/vagrant-init-database.sh
scripts/vagrant-provision.sh

This PR is a branch from https://github.com/liveblog/liveblog/pull/738
https://dev.sourcefabric.org/browse/LBSD-1473

Hide delete button when editing

---

client/app/scripts/liveblog-edit/styles/liveblog-edit.scss

https://dev.sourcefabric.org/browse/LBSD-1518

Fix instructions appearing twice in liveblog-edit

---

client/app/scripts/liveblog-bloglist/module.js

https://dev.sourcefabric.org/browse/LBSD-1556

Fixed issues members not being counted

---

.travis.yml
server/liveblog/syndication/consumer.py
server/liveblog/syndication/syndication.py
server/liveblog/syndication/tasks.py
server/liveblog/syndication/utils.py
server/settings.py

- Fix webhook status check for consumers (LBSD-1345)
- Set SYNDICATION_VALIDATE_AUTH on travis env.
- Cast project env settings variables to fallback value type.
- Handle boolean and string environment setting values.

LBSD-1345: Fix webhook status check for consumers

---

client/app/scripts/ng-sir-trevor-blocks.js

https://dev.sourcefabric.org/browse/LBSD-1498

Fixed quote issue

---

client/app/styles/sass/liveblog.scss

https://dev.sourcefabric.org/browse/LBSD-1489

Fix highlight orange

---

client/app/scripts/liveblog-edit/directives/posts-list.js

https://dev.sourcefabric.org/browse/LBSD-1521

Fixed syndicated posts not being updated on the consumer end

---

client/app/scripts/ng-sir-trevor-blocks.js

https://dev.sourcefabric.org/browse/LBSD-1525

Fixed syndicated image not being displayed on edit

---

client/app/scripts/liveblog-bloglist/module.js
client/bower.json

* https://github.com/liveblog/superdesk/pull/11
* https://dev.sourcefabric.org/browse/LBSD-1570

Reference to correct superdesk commit

---

README.md
client/app/scripts/liveblog-themes/module.js

The fix on prod: https://team.liveblog.pro/#/themes/
and the relevant ticket https://dev.sourcefabric.org/browse/LBSD-1568

Fixed minify error on prod

---

client/app/scripts/liveblog-advertising/styles/advertising.scss
client/app/scripts/liveblog-advertising/views/advert-modal.html
client/app/scripts/liveblog-bloglist/views/main.html
client/app/scripts/liveblog-edit/directives/freetype-image.js
client/app/scripts/liveblog-edit/views/freetype-image.html

Because modal upload breaks other modals with free type images

LBSD-1571 Change freetype image upload from modal to plain

---

server/liveblog/syndication/syndication.py
server/requirements.txt
server/settings.py

Updated requirements.txt to use superdesk-core version 1.6 instead of 1.7.

Revert superdesk-core to version 1.6

---

client/app/scripts/liveblog-edit/controllers/blog-settings.js
client/app/scripts/liveblog-edit/directives/output-modal.js
client/app/scripts/liveblog-edit/styles/liveblog-edit.scss
client/app/scripts/liveblog-edit/views/output-embed-code-modal.html
client/app/scripts/liveblog-edit/views/output-modal.html
client/app/scripts/liveblog-edit/views/settings.html

Present embed code with selected output

LBSD-1580 Present embed code for selected output

---

server/liveblog/syndication/tasks.py
server/liveblog/syndication/utils.py

There was a reference to the current request in code being called from a task

Removed reference to request in task which caused an error

---

client/app/scripts/liveblog-edit/pages-manager.service.js

Can someone tell me, what on earth is this line supposed to do?
LBSD-1522

Remove wrong post on unpublished

---

client/app/scripts/liveblog-syndication/directives/consumer-edit.js

https://dev.sourcefabric.org/browse/LBSD-1515

Wrong error message for unique webook

---

client/app/scripts/liveblog-bloglist/directives/user-select-list.js

https://dev.sourcefabric.org/browse/LBSD-1601

Added missing function to display the name

---

client/app/scripts/liveblog-syndication/styles/syndication.scss
client/app/scripts/liveblog-syndication/views/consumer-edit-form.html
client/app/scripts/liveblog-syndication/views/producer-edit-form.html

* https://dev.sourcefabric.org/browse/LBSD-1602
* https://github.com/liveblog/superdesk-client-core/pull/1

Fix conflicting styling issue between user management and syndication

---

client/app/scripts/liveblog-bloglist/styles/liveblog-bloglist.scss
client/app/scripts/liveblog-bloglist/views/main.html

https://dev.sourcefabric.org/browse/LBSD-1603

Create blog button should be on the right side

---

client/app/scripts/liveblog-syndication/directives/ingest-panel.js
client/app/scripts/liveblog-syndication/reducers/ingest-panel.js

https://dev.sourcefabric.org/browse/LBSD-1513

Fixed syndication ingest notification counting although autopublish is on

---

client/app/scripts/liveblog-edit/controllers/blog-settings.js

https://dev.sourcefabric.org/browse/LBSD-1620

Fixed invalid date in settings causing issue on team assignment

---

client/app/scripts/liveblog-themes/views/list.html
server/liveblog/syndication/tasks.py

fix: info text for Themes Management.

---

server/liveblog/themes/themes.py

version all the file in the theme,
except the `parent-iframe.js`.

fix: theme file version.

---

client/app/scripts/liveblog-marketplace/directives/search-filter.js
client/app/scripts/liveblog-marketplace/directives/search-panel.js
client/app/scripts/liveblog-marketplace/index.js
client/app/scripts/liveblog-marketplace/views/search-filter.html
client/app/scripts/liveblog-marketplace/views/search-panel.html

* Deactivated accordion search filter
* Directive for search filter
* Language filter

Various fixes for the marketplace

---

client/app/scripts/liveblog-edit/views/settings.html

introduce a control that would help user navigating back to the blog's
authoring

LBSD-1613 back to blog authoring

---

client/app/scripts/liveblog-edit/controllers/blog-edit.js
client/app/scripts/liveblog-syndication/directives/ingest-panel.js
client/app/scripts/liveblog-syndication/directives/notifications-count.js

* Should not update the notification count in ingest panel when publishing an ingested post
* Should reset the notification count in ingest panel when leaving the view
* Fix broken tooltip notification count (ingest logo)

Various notification fixes for syndication

---

client/app/scripts/sir-trevor-blocks/index.js

Sir trevor added header formatting

---

client/app/scripts/sir-trevor-blocks/index.js

fix: removed by keyword, fixed html markup

---

client/app/scripts/liveblog-edit/controllers/blog-settings.js
client/app/scripts/liveblog-marketplace/directives/search-panel.js
server/liveblog/blogs/schema.py

Added two new blog categories

---

client/app/scripts/liveblog-freetypes/module.js
client/app/scripts/liveblog-freetypes/views/list.html
server/liveblog/items/items.py

feature: added notification for freetypes used.

---

client/app/scripts/liveblog-advertising/styles/advertising.scss
client/app/scripts/liveblog-advertising/views/collection-modal.html
client/app/scripts/liveblog-bloglist/styles/liveblog-bloglist.scss
client/app/scripts/liveblog-edit/styles/settings.scss
client/app/scripts/liveblog-edit/views/settings.html
client/app/scripts/liveblog-freetypes/styles/freetypes.scss
client/app/styles/sass/liveblog.scss

- fixed missing scroll in Advertising views
- added space in the collection list (modal)
- fixed subnav button position in Analytics page
- fixed nav button border, active state (button group
analytics/settings)
- freetypes list position fix

UI fixes and improvements

---

server/requirements.txt

Ref: https://dev.sourcefabric.org/browse/SDESK-1957

Update superdesk-core with fix for [SDESK-1957]

---

client/app/scripts/liveblog-edit/blog.service.js
client/app/scripts/liveblog-edit/controllers/blog-settings.js
server/liveblog/blogs/templates/embed.html

fix: replace http with https for embed code added async.

---

server/liveblog/advertisements/advertisements.py
server/liveblog/blogs/schema.py
server/liveblog/items/items.py
server/liveblog/posts/posts.py
server/liveblog/themes/themes.py

fix: mappings and publisher.

---

client/app/scripts/liveblog-edit/controllers/blog-edit.js

https://stackoverflow.com/questions/1732348/regex-match-open-tags-
except-xhtml-self-contained-tags

fix: removed valid html parsing from sirtrevor with regex.

---

server/liveblog/themes/template/filters.py
server/liveblog/themes/themes.py

feature: ninja2 ampify.

---

client/app/scripts/liveblog-edit/controllers/blog-edit.js
client/app/scripts/liveblog-edit/views/main.html
client/scripts/test_e2e.sh

https://dev.sourcefabric.org/browse/LBSD-2036

Warn the user of unsaved content when exiting the current blog

---

client/app/scripts/liveblog-edit/controllers/blog-edit.js

fix: update edited post.

---

client/app/scripts/liveblog-edit/freetype.service.js
client/app/scripts/liveblog-edit/views/scorecards.html

feature: limit scorecard fields.

---

client/app/scripts/liveblog-edit/views/settings.html

https://dev.sourcefabric.org/browse/LBSD-2000

Fix: made avatar pic displayed everywhere in blog settings/team section

---

client/app/scripts/liveblog-edit/controllers/blog-edit.js
client/app/scripts/sir-trevor-blocks/image-block.js
client/app/scripts/sir-trevor-blocks/index.js

fix: passed `syndicated_creator` property to new items.

---

client/app/scripts/liveblog-bloglist/directives/user-select-list.js
client/app/scripts/liveblog-edit/views/settings.html
client/spec/blogs_list_spec.js

https://dev.sourcefabric.org/browse/LBSD-2066
New comment fix

fix: Included admin and excluded blog owner from users list

---

client/app/scripts/liveblog-edit/directives/freetype-image.js

https://dev.sourcefabric.org/browse/LBSD-2103

fix: Changed the enable publish button state

---

client/app/scripts/liveblog-edit/controllers/blog-edit.js
client/app/scripts/liveblog-edit/directives/posts-list.js
client/app/scripts/liveblog-edit/views/post.html
client/app/scripts/ng-sir-trevor.js
client/app/scripts/sir-trevor-blocks/index.js
client/app/scripts/sir-trevor-blocks/sanitizer-config.js
client/package.json

Hi @nistormihai, please have a look of this when you have some time. Is it `devel` the right base branch in this case? Thanks!

LBSD-2148 fix: misbehaviour of Sir Trevor on content paste

---

client/app/scripts/liveblog-edit/module.js
client/app/scripts/liveblog-edit/views/post.html

feature: auto updating relative date on posts list

---

client/app/scripts/liveblog-edit/directives/posts-list.js

fix: allow scorecards edit.

---

client/app/scripts/liveblog-edit/views/scorecards.ng1

https://dev.sourcefabric.org/browse/LBSD-2157

fix: changed score card labels in scorecard post

---

server/liveblog/freetypes/__init__.py
server/liveblog/freetypes/commands.py
server/liveblog/freetypes/freetypes.py
server/liveblog/themes/__init__.py
server/liveblog/themes/commands.py
server/liveblog/themes/themes.py

feature: added `register_theme` and `register_freetype` commands

---

client/app/scripts/liveblog-edit/posts.service.js

feature: allow unpublished posts in contributions.

---

server/liveblog/client_modules/client_modules.py
server/liveblog/client_modules/client_modules_test.py

https://dev.sourcefabric.org/browse/LBSD-2131

Test case/client modules

---

server/liveblog/themes/themes_assets/classic/views/posts.html

https://dev.sourcefabric.org/browse/LBSD-2135

fix: fixed classic theme slideshow issue

---

client/package.json

https://dev.sourcefabric.org/browse/LBSD-2177

fix: downgraded angular-embed version to 2.1.1

---

client/app/scripts/liveblog-edit/views/settings.ng1
client/app/scripts/liveblog-settings/views/general.ng1
client/app/styles/sass/liveblog.scss

Fixed issue with automation test for blog settings

---

server/liveblog/themes/themes_assets/default/theme.json

https://dev.sourcefabric.org/browse/LBSD-2181

feature: Default theme: introduce theme setting to hide sorting options

---

server/liveblog/client_modules/client_modules.py
server/settings.py

fix: AMP-Access-Control-Allow-Source-Origin

fix: set AMP-Access-Control-Allow-Source-Origin dynamic

---

server/liveblog/client_modules/client_modules.py

fix: amp commenting for all instances

---

client/app/scripts/liveblog-edit/directives/freetype-text.js

LBSD-2187 fix: scorecard validation issue

---

client/app/scripts/liveblog-bloglist/views/main.ng1
client/app/scripts/liveblog-edit/views/freetype-image.ng1

https://dev.sourcefabric.org/browse/LBSD-2220

fix: remove image does not really remove it from blog AdLocal

---

client/app/scripts/liveblog-bloglist/views/main.ng1

https://dev.sourcefabric.org/browse/LBSD-2240

fix:Dashboard shows wrong timestamp for blogcreation and blogupdate

---

server/liveblog/client_modules/client_modules.py

https://dev.sourcefabric.org/browse/LBSD-1821

fix: support social media icons for multi item posts

---

server/liveblog/auth/db.py

https://dev.sourcefabric.org/browse/LBSD-2227

fix: hide sd browser notification pop up

---

client/app/scripts/liveblog-themes/module.js
client/app/scripts/liveblog-themes/theme-settings-modal.js
client/app/scripts/liveblog-themes/views/list.ng1
client/app/scripts/liveblog-themes/views/theme-settings-modal.ng1

fix: added dynamic theme options in theme manager

fix: added dynamic theme options in theme manager

---

client/app/scripts/liveblog-themes/module.js

fix: remove angular theme from theme options in theme manager

fix: removed angular theme from theme options

---

client/app/scripts/liveblog-edit/directives/freetype-image.js

https://dev.sourcefabric.org/browse/LBSD-2246

fix: issue with score card image

---

server/liveblog/auth/db.py

fix: to make disable SD pop up method more water proof.

fix: issue with sd pop up hide method

---

client/app/scripts/liveblog-edit/directives/freetype-text.js

https://dev.sourcefabric.org/browse/LBSD-2191

fix: Required field names in scorecards are not marked

---

client/package.json

I did not check if it is working with node v6.14.2 too (Latest LTS: Boron), but I hope it does 😊

Update node-sass to work with current node LTS (v8.11.1)

---

client/app/scripts/liveblog-themes/module.js
client/app/scripts/liveblog-themes/views/list.ng1

https://dev.sourcefabric.org/browse/LBSD-2249

fix: hide user notifications in theme settings, if they have been closed

---

client/app/scripts/liveblog-syndication/directives/incoming-syndication.js

https://dev.sourcefabric.org/browse/LBSD-2236

fix: Ingested channel has to be revisited in order for reposts to appear

---

client/app/scripts/liveblog-edit/views/settings.ng1

https://dev.sourcefabric.org/browse/LBSD-2257

fix:limited the management of max number of posts to the user role admin

---

client/app/scripts/liveblog-edit/controllers/blog-settings.js
client/app/scripts/liveblog-edit/views/settings.ng1

https://dev.sourcefabric.org/browse/LBSD-2257

fix: posts limit access limit to admin only

---

client/webpack.config.js

https://dev.sourcefabric.org/browse/LBSD-2259

fixed: Set theme restriction from 3 to 5  for team subscription

---

client/app/scripts/liveblog-advertising/activities.js
client/app/scripts/liveblog-edit/views/main.ng1
client/app/scripts/liveblog-freetypes/module.js

https://dev.sourcefabric.org/browse/LBSD-2269

removed beta labels from user interface of Live Blog

---

docs/apiary.apib

https://dev.sourcefabric.org/browse/LBSD-2254

set response for subscription check auth_db api

---

server/liveblog/posts/posts.py

fix: issue with amp comments are not displaying in the blog's live page.

fixed: amp comments not showing in front end after publishing

---

docs/apiary.apib

https://dev.sourcefabric.org/browse/LBSD-2271

documented the new commenting api endpoint in apiary

---

README.md
client/app/index.html
client/package.json
package.json
server/liveblog/auth/__init__.py
server/liveblog/auth/reset_password.py
server/liveblog/utils/hooks/__init__.py
server/liveblog/utils/hooks/events.py
server/settings.py

Introduce first implementation of hook triggering after certain users' actions. At the moment we're only triggering on `user_activation` but we will introduce more hooks soon.

Release v3.6.2

---

client/app/scripts/liveblog-edit/controllers/blog-edit.js
client/app/scripts/liveblog-edit/unread.posts.service.js
server/liveblog/client_modules/client_modules.py
server/liveblog/posts/posts.py

- Added code to stop listening to previous blog if the user opened a new blog
- Fixed same comment count for all blogs

LBSD 2391 wrong comment count

---

README.md
docker/requirements.txt
server/liveblog/themes/themes_assets/amp/less/tags.less
server/liveblog/themes/themes_assets/amp/templates/template-item-gallery.html

Added the style element to unset the height attribute for positioning the arrows with respect to the image

LBSD 2480 position slideshow arrows

---

.travis.yml

- Upgraded travis configuration to use Ubuntu Bionic
- Fixed and simplified configuration files (using docker for Elasticsearch 1.7 and MongoDB 3)

LBSD-2509 TravisCI config upgrade

---

client/app/scripts/liveblog-edit/blog.service.js
client/app/scripts/liveblog-edit/controllers/blog-edit.js
client/app/scripts/liveblog-edit/views/main.ng1
client/package.json
client/webpack.config.js
server/liveblog/blogs/tasks.py

Updates:
- Hide Live link until public_url is received
- Use EMBED_PROTOCOL for setting Live link's protocol

LBSD-2492 Update Live Link

---

server/liveblog/themes/themes_assets/angular/liveblog-embed/directives.js
server/liveblog/themes/themes_assets/angular/liveblog-embed/pages-manager.service.js
server/liveblog/themes/themes_assets/classic/styles/dropdown.css

- Fixed an issue in classic theme where selecting a tag and then switching order fetched all posts regardless of the tags applied
- Fixed classic theme dropdown width

Classic theme dropdown fixes

---

client/app/scripts/liveblog-bloglist/styles/liveblog-bloglist.scss

Resolves LBSD-2753
Limits description preview for blog list grid and list view using CSS ellipsis and line clamp

Limit description preview in both grid view and list view

---

server/liveblog/client_modules/client_modules_test.py
server/liveblog/polls/__init__.py
server/liveblog/polls/polls.py
server/liveblog/polls/tests/polls_test.py
server/liveblog/posts/posts.py
server/liveblog/syndication/utils.py
server/settings.py

This PR introduces the functionality of incorporating polls into posts as a new variation of items that can be used. A summary of the key objectives and the implemented solutions are as follows:
A new collection named `polls_collection` has been added to our database. This collection is designed to store poll data, including questions, options, and votes, allowing for dynamic interaction within blogs.
Implementation of new endpoints to support Create, Read, Update, and Delete (CRUD) operations for polls. These endpoints facilitate the management of poll data, enabling users to easily create new polls, view existing polls, update poll details, and remove polls when necessary.
The existing endpoint for post items has been adjusted to include the functionality of attaching polls. This …

[LBSD-2762] - Implement backend logic to store and manage polls in the Editor's interface

---

server/liveblog/client_modules/__init__.py
server/liveblog/client_modules/client_modules.py
server/liveblog/client_modules/client_modules_test.py
server/liveblog/posts/utils.py

This PR implements endpoints on the clients side to get polls within posts and allow readers to vote on them. 
- **Updated endpoint for getting posts:** The existing endpoint for fetching blogs posts on the clients side has been updated to  attach the poll data.
- **New Endpoint for Voting:** A patch endpoint has been introduced to enable readers to cast their votes on polls. This endpoint handles vote submission and updates the poll results.
- Endpoints can be tested using a third party app or service like Postman. Also curl can be used to test the endpoints.
```
curl --location --request GET 'http://127.0.0.1:5000/api/v2/client_blogs/<blog_id>/posts'
```
```
curl --location --request GET 'http://127.0.0.1:5000/api/client_polls'
```
```
curl --location --request GET …
```

[LBSD-2765] - Implement the backend logic to display polls in the readers' side

---

server/liveblog/themes/themes_assets/amp/package.json
server/liveblog/themes/themes_assets/amp/templates/template-post.html
server/liveblog/themes/themes_assets/amp/theme.json

This PR ensures that the Poll feature completed in [LBSD-2768](https://github.com/liveblog/liveblog/pull/1363) works on the Simple theme and the AMP theme.
- For the Simple theme, the Poll feature works like the Default theme on the embeds.
- Fort he AMP theme, the Poll feature is not rendered for now on the embeds.
1. Navigate to the Editor's interface and create a new Blog and for the theme select Simple Theme
2. Click "Add content here" and select Poll. Fill the poll form and submit. The poll will appear on the timeline.
3. Click "Live" to see the Live Preview. You will see the poll UI when open.
1. Navigate to the Editor's interface and create a new Blog and for the theme select AMP Theme
2. Click "Add content here" and select Poll. Fill the poll form and submit. The poll will appear …

[LBSD-2775] - Implement Poll feature for Simple and AMP theme

---

server/liveblog/prepopulate/app_initialize.py
server/liveblog/prepopulate/data_init/instance_settings.json

The purpose of this PR is to include the instance settings fixture file introduced in [LBSD-2782](https://github.com/liveblog/liveblog/pull/1375) in the `app:initialize_data` command so that the default config can be loaded on instance creation.
- **Added fixture file to command resources** - Added the instance fixture file to the list of resources used by the `initialize_data` command.
- **Changed fixture file format** - Modified the fixture file format to be an array with the settings object in it to resemble other fixture files and avoid error on running the command.
1. Check out to the branch
2. Move into the server directory and initialize the app using the command : 
```
$ cd server
$ python3 manage.py app:initialize_data;
```
3. Send a GET request as outlined in …

[LBSD-2790] - Include the Instance Settings fixture file in the intialize_data command

---

server/liveblog/posts/posts.py

This PR changes the implementation on how the blog data update is handled on creating scheduled posts. 
- For scheduled posts, the `update_post_blog_data` is skipped.
1. Open the Editor.
2. Publish a normal post. Check the blog data on the client blog endpoint i.e : 
```
$ curl http://127.0.0.1:5000/api/client_blogs/66a34e2233bb0826712c3e8c
```
Observe that the `last_created_post` attribute has been updated. 
3. Publish a scheduled post. Check the blog data on the client blog endpoint i.e : 
```
$ curl http://127.0.0.1:5000/api/client_blogs/66a34e2233bb0826712c3e8c
```
Observe that the `last_created_post` attribute has not been updated. 
Resolves: [LBSD-2837](https://sofab.atlassian.net/browse/LBSD-2837)
[LBSD-2837]: https://sofab.atlassian.net/browse/LBSD-2837?atlOrigin=eyJpIjoiNWRkNTljNz …

[LBSD-2837] - Skip update blog data for scheduled posts

---

server/liveblog/client_modules/client_modules.py

This PR improves on the Poll feature where when a vote is placed, it also updates the `content_update_date` so that the embeds can capture the update and display the updates in votes on the timeline.
- Update the `content_update_date` on the parent post of a poll. 
1. Open the Editor and publish a new poll.
2. Open the Live Preview in multiple browsers. 
3. Place votes randomly and observe that the other clients show the updates of the total votes and the voting tally periodically
[polls-update.webm](https://github.com/user-attachments/assets/d9cdd882-f61b-4600-ad76-ec0d5d1e5e3f)
Resolves: [LBSD-2864](https://sofab.atlassian.net/browse/LBSD-2864)
[LBSD-2864]: https://sofab.atlassian.net/browse/LBSD-2864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU …

[LBSD-2864] - Update post on poll  vote
