liveblog/liveblog

- server/app.py
Save all our problems and probably the world too
- mixed items order
- 500 when we do several requests at the same time
- mixed fields in responses
Because our dependencies are not safe for multithread.
> multiprocessing removed from backend server

- server/requirements.txt
The current version in requirements.txt for python3-ldap is somehow
missing and this causes Travis tests to fail. An increase should fix it
> LBSD-431 Increase version for python3-ldap

- client/app/scripts/liveblog-edit/directives.js
- client/app/scripts/liveblog-edit/module.js
> Timeline small fixes (LBSD-11)

- client/app/scripts/liveblog-edit/views/settings.html
It seems that for now when using ngOptions the select and label
expressions( as in select as label for value in array) can't be equal. Small hack until Angular fixes the problem.
> LBSD-38 Fix theme selection

- .travis.yml
- server/app.py
- server/apps/prepopulate/app_prepopulate_data.json
- server/liveblog/blogs/blogs.py
- server/liveblog/client_modules/client_modules.py
- server/liveblog/common.py
- server/liveblog/embed/embed_assets/scripts/liveblog-embed/resources.service.js
- server/liveblog/posts/posts.py
- server/liveblog/themes/themes.py
- server/requirements.txt
- Introduces a new class `BlogCache` to access the cache associated to a blog
- Uses Flask-Cache as interface to the cache system.  
For now we are using SimpleCache, a simple memory cache from [werkzeug](http://werkzeug.pocoo.org/docs/0.10/contrib/cache/#werkzeug.contrib.cache.SimpleCache)
- Dissociates user information from posts to not make the cache more complex
- Remove server_ldap from travis tests
> Feature/cache [LBSD-541]

- client/app/scripts/liveblog-edit/module.js
- client/app/scripts/liveblog-edit/views/main.html
When publishing a post, the "PUBLISH" button should get disabled after
the user clicks on it for the first time. Currently, the user can
publish the same post multiple times to the timeline by repeatedly
clicking on the "PUBLISH" button while the first request is still
processing.
> LBSD-593 User should only be able to publish an article one time

- client/app/index.html
The permanent Javascript version that gets the current year breaks the modal window( and that may not even show the real date as it is easily manipulated by the client) so there... hardcoded
> LBSD-827 Fix the about year

- client/app/scripts/liveblog-edit/module.js
- client/app/scripts/liveblog-edit/views/main.html
Draft button should be disabled or hidden when a user opens a
contribution created by another user
> LBSD-828 Disable draft button if not owner

- client/app/scripts/liveblog-bloglist/module.js
- client/app/scripts/liveblog-bloglist/views/main.html
When pressing the Enter key in the title field, an unwanted "Add to dictionary" dialog opened in the blog description area. Now the Enter key forwards the form to the next page if the condition is met.
> LBSD-1029 Prevent form submit on Enter key

- client/app/scripts/liveblog-syndication/directives/consumer-edit.js
- client/app/scripts/liveblog-syndication/views/consumer-edit-form.html
- client/app/scripts/liveblog-syndication/views/consumer-list-item.html
- client/app/scripts/liveblog-syndication/views/consumer-list.html
- server/features/syndication_consumers.feature
- server/features/syndication_producers.feature
- server/liveblog/syndication/consumer.py
Add api_url to consumer resource. We need to add api_url to consumer resource. This is required to get the syndication webhook working. We no longer need to define a target_url for syndicate webhook.
> LBSD-1091:  Add api_url to consumer resource

- server/liveblog/syndication/syndication.py
New and old posts are now posted by using post_status "open" if auto_publish is set to True and with post_status "submitted" if auto_publish is set to False
> Autopublish fix.

- client/app/scripts/liveblog-analytics/controllers/controller-analytics.js
- client/app/scripts/liveblog-analytics/views/view-analytics.html
Transform analytics items to CSV, download via `link.download` as opposed to `window.open`. Should work with any HTML5 capable browser and IE, cf. http://caniuse.com/#search=download. Code is linted this time around.
> Add download CSV functionality to analytics view

- client/app/scripts/liveblog-bloglist/module.js
- client/app/scripts/liveblog-bloglist/views/main.html
- client/app/scripts/liveblog-edit/controllers/blog-settings.js
- client/app/scripts/liveblog-edit/views/settings.html
- client/app/scripts/liveblog-security.service.js
- client/tasks/options/template.js
This PR is doing two things:
* Displaying a modal inviting the user to upgrade when trying to create more blogs than allowed.
* In blog settings, checking the number of active blogs before allowing to change the status from `archived` to `open`.
> LP-34 - In client, limit number of active blogs depending on subscription level

- client/app/scripts/liveblog-themes/module.js
- client/app/scripts/liveblog-themes/views/list.html
- client/tasks/options/template.js
Limit the number of allowed themes to 3 (excluded angular theme) for team instances.
> LP-40 - On client, limit number of themes for users with team level subscription

- Vagrantfile
@m0g, this should play nice across platforms. One can avoid provisioning of all providers at once by altering `config.vm.box_url` conditionally, in effect just replacing urls for a shared box. I'd be happy to commit this on another branch if you like.
> Add multi-platform support to Vagrantfile

- client/app/scripts/liveblog-edit/views/main.html
- client/app/scripts/liveblog-freetypes/views/list.html
In order to keep the design from breaking in the editor when a freetype is selected, I limited the length of the freetype title shown to 32 characters. The actual title in the CRUD is limited to 65 chars for the similar reasons
If this is not an option then we have to reevaluate the design.
> LBSD-1272 limit freetype title length

- client/app/index.html
- client/app/scripts/liveblog-edit/views/settings.html
- client/app/scripts/liveblog-marketplace/directives/marketplace-switch.js
- client/app/scripts/liveblog-marketplace/views/marketplace-switch.html
In blog settings, the market switch is now a separate directive belonging to the `liveblog-marketplace` module.
This allows an easy removal of the market switch in case the `liveblog-marketplace` module is deactivated.
> Added a marketplace switch in blog settings

- client/app/scripts/liveblog-themes/module.js
- client/app/scripts/liveblog-themes/views/list.html
* Restore theme manager for `solo` users
* Hide open source alert message
* Hide github link in themes list
* Hide new theme button
* Hide download theme
> Lp 49 - Restore theme manager access for solo users (SAAS)

- client/app/scripts/liveblog-edit/styles/liveblog-edit.less
- client/app/scripts/liveblog-edit/views/main.html
LBSD-1358 Add "helper texts" to main navigation icons in the blog editor
LBSD-1337 UI issue with the button to select an image from folder
> fix button height and tooltips

- client/app/scripts/liveblog-edit/styles/liveblog-edit.less
adding certain type of edge URL breaks the Liveblog UI
Example of such URL is AK%22%20style%3D%22background:url(javascript:alert(%27XSS%27))%22%20OS%22
> LBSD-1353 Fix styling issue

- client/app/scripts/liveblog-edit/directives.js
- client/app/scripts/liveblog-edit/views/main.html
- client/app/scripts/liveblog-edit/views/post.html
Added the following when viewing an archived blog:
* Deactivate blog actions in the timeline (moved, delete, star...)
* Deactivate the Live link
> LBSD-1402 Deactivate blog actions when archived

- client/app/scripts/liveblog-edit/directives.js
> take the embed URL for an Instagram post
> try publishing it
> Observe that while in preview the image appears within a relatively acceptable timeframe, once it gets published the image post does not appear in the right panel, unless another post is triggered from the left one.
> LBSD-1351 Sorted out embed instagram issue

- client/app/scripts/liveblog-edit/views/main.html
LBSD-1377
Purpose of the preview button for post types other than default
LBSD-1358
Add "helper texts" to main navigation icons in the blog editor
> preview button hidden for free types and more tooltips

- server/liveblog/syndication/__init__.py
- server/liveblog/syndication/syndication.py
Change privilege name to sort out this issue.
`syndication_in` was being returned inside elastic search post query as part of the user `active_privileges` object. Therefore querying for an post with a missing `syndication_in` key would not work.
> LBSD-1305 When I click on button to "unpublish and save in contributions" by a post in timeline, post does not appear in contributions

- client/app/scripts/ng-sir-trevor-blocks.js
- client/tasks/options/template.js
Maximum image upload size can be set via environment variable otherwise defaults to 8MB.
> LBSD-1355 Limit maximum upload image size

- server/liveblog/blogs/blogs.py
- server/liveblog/syndication/blogs.py
- server/liveblog/syndication/syndication.py
dirrect access is causing errors when blogs don't has
`syndication_enabled` property at all.
> hotfix: use `get` method for `syndication_enabled`.

- client/tasks/options/template.js
For Live Blog Solo (Solo Mobile): Change max number of team members from 3 to 2.
For Live Blog Team: Change max number of team members from 5 to 4.
> LP-63 change number of allowed users for subscriptions of type solo and team

- .travis.yml
It's now possible to add environment variables directly via the admin interface, thus enabling the possibility of making PRs from forks.
https://travis-ci.org/liveblog/liveblog/settings
> Remove travis encryption

- server/app.py
- server/settings.py
On new database without blogs when I run
```sh
./manage.py app:initialize_data
./manage.py register_local_themes
./manage.py app:initialize_data
./manage.py register_local_themes
WARNING:elasticsearch:GET /lbpr-744/blogs/_search [status:404 request:0.001s]
DEBUG:elasticsearch:> {"sort": [{"_updated": "desc"}], "query": {"filtered": {"filter": {"and": [{"and": [{"term": {"blog_preferences.theme": "classic"}}]}]}}}}
DEBUG:elasticsearch:< {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"lbpr-744","index":"lbpr-744"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"lbpr-744","index":"lbpr-744"},"status":404}
INFO:superdesk:Uhoh, an exception occured …
```
> Fix deployment issue

- client/app/scripts/liveblog-edit/posts.service.js
- client/app/scripts/liveblog-edit/styles/post.scss
- client/app/scripts/liveblog-edit/views/post.html
Multiple items is now camel case and representing the number of items that are currently hidden in the timeline view. In opposition to display the count of all the items for the post.
> LBSD-1448 fix wrong item count

- server/liveblog/syndication/syndication.py
- server/requirements.txt
- server/settings.py
* Revert to superdesk-core 1.6
* Update bcrypt and cffi packages
* Add CONTENTAPI_URL setting
* Remove duplicated dependencies in requirements.txt.
* Use client_blogs instead of blogs resource to prevent permission errors.
> Revert superdesk-core to version 1.6 (#777)

- server/liveblog/marketplace/blogs.py
- server/settings.py
The endpoint was returning blogs which hadn't been enabled in the market
> Fixed filter on marketed blogs endpoint

- client/app/scripts/liveblog-edit/controllers/blog-edit.js
- client/app/scripts/sir-trevor-blocks/image-block.js
"Add content" button is invisible after halting the upload process of a
larger image implying that termination is not working
> LBSD-1617 Publish button not visible after canceling large image upload

- client/app/scripts/liveblog-edit/views/scorecards.html
- client/spec/editor_scorecards_spec.js
When changing from an unchanged/unsaved scorecard there should not be a
confirmation popup
> LBSD-1434 Scorecards unnecessary confirmation popup

- server/liveblog/items/items.py
- `original_id` for instagram doesn't need to contain the trailing slash.
> fix: instagram `original_id` don't need to contain slash.

- server/liveblog/themes/template/filters.py
I want to support relative dates in AMP templates too, so the idea is to enable something like `{{ postDate | date('ago') }}`. You already support this format for templates parsed by nunjucks, see https://github.com/liveblog/liveblog/blob/9c134ec1538f3fd58050c043d7cea44f8bb9471e/server/liveblog/themes/themes_assets/default/js/theme/helpers.js#L13-L15
> Add support for relative date format

- server/liveblog/blogs/templates/embed_amp.html
There is a closing `</amp-analytics>` tag in every AMP liveblog.
> Fix: Close <amp-analytics> tag correctly

- server/liveblog/blogs/templates/embed_amp.html
Support relative dates (like "a minute ago") in AMP templates.
> feature: add <amp-timeago> for relative dates

- .travis.yml
After long time of research, tests and figuring out it seems like the
simplest way to achieve this is using a "test" key while running our e2e
tests and this way allow cross-fork pull requests
> LBSD-1957 Implement embedly key on Travis

- client/package.json
I'm pointing temporarily to until official is updated with the PR I opened to fix this issue superdesk/angular-embed#8
Expecting to change this package url before release 3.4 version
This is also related to #1144
> LBSD-2177 fix: Instagram embeds are not working

- server/liveblog/themes/themes_assets/simple/README.md
- server/liveblog/themes/themes_assets/simple/package.json
- server/liveblog/themes/themes_assets/simple/theme.json
I also published the theme to npmjs.com in order to make it available in generator. https://www.npmjs.com/package/liveblog-simple-theme
We should republish after merging this.
> LBSD-2185 Small changes to Simple theme to enable it in generator

- server/liveblog/themes/themes.py
Also adding `template` to ignored fields since it's a heavy field and makes the calculation of etag slower.
> LBSD-2205 fix: Cannot save changes in any of the themes

- client/app/styles/sass/liveblog.scss
- client/package.json
The rest of the things were already adjusted in main `superdesk-client-core` repo. This is related to superdesk/superdesk-client-core#2320
> LBSD-2196 fix: hide language option from user's profile

- server/liveblog/themes/themes_assets/default/js/theme/handlers.js
> fix: don’t load deleted posts when toggling highlighted

- client/app/scripts/liveblog-edit/controllers/blog-edit.js
- server/liveblog/blogs/embeds.py
- server/liveblog/blogs/utils.py
- server/liveblog/posts/posts.py
- server/setup.cfg
The problem was that the post taken for deletion was the oldest loaded in the timeline (browser side), that caused the removing of recent posts.
Instead of taking the one from timeline we must query the oldest one in database for the current blog and mark it as deleted.
> LBSD-2278 Fixes deleting bug when blog posts_limit has been reached

- server/liveblog/themes/themes_assets/default/tasks/templates.js
Fixed cross-platform path separator problem
> cross-plattform path seperator in template.js

- client/package.json
Reverts liveblog/liveblog#1274 because tests are not ready for this version of angular
> Revert "Bump angular from 1.6.9 to 1.7.9 in /client"

- client/app/scripts/sir-trevor-blocks/video-block.js
The issue was if we delete the video from the post, the "add content here" button disables. Now add-content method added in onError and onComplete to show the "add content here" button if video is deleted.
> LBSD-2522 Show add-content button onError and onComplete

- server/liveblog/client_modules/client_modules.py
There is an undesired behaviour in new endpoint for output channels posts, if we pass an output_channel_id which is not present, the API is returning 500 internal server error. The issue is fixed by adding SuperdeskApiError class methods to handle errors, Now the API endpoint will return 404 not found for an output_channel_id which is not present.
> undesired behaviour in output channels posts endpoint fixed.

- .github/workflows/continuous-integration.yml
- server/liveblog/themes/themes_assets/angular/liveblog-embed/resources.service.js
Classic theme is filtering tagged content sending an ElasticSearch query from the frontend. Now we have updated classic theme to use new endpoint for output channels posts to filter tagged content.
> LBSD-2458 Updated classic theme to use output post endpoint

- README.md
Updated the setup steps using Ubuntu version 20.04.6 LTS. 
Marked the "Liveblog Setup Using Docker" as outdated. 
Removed the "Vagrant LXC Installation" section.
> Resolves LBSD-2750

- .gitignore
- client/app/scripts/sir-trevor-blocks/embed-block.js
- client/app/scripts/sir-trevor-blocks/helpers/input-change-tracker.ts
- client/app/scripts/sir-trevor-blocks/image-block.js
This fixes the bug of the publish button not getting enabled when any modifications are made to an item of type image in the editor
- Added a new simple change tracker for inputs taking existing logic in `embed-block.js`
- Adjusted `embed-block.js` to use new tracker
- Implemented usage of new tracker in `image-block.js` to fix the problem
- Create a post (media) and save it to drafts
- Go to drafts section and edit the post
- Notice the publish button does activate
Thanks for reviewing!
Resolves: [LBSD-2726]
[LBSD-2726]: https://sofab.atlassian.net/browse/LBSD-2726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LBSD-2726] Publish button not activating on draft edited

- client/app/scripts/liveblog-bloglist/views/main.ng1
- client/app/scripts/liveblog-edit/views/post.ng1
This PR fixes a bug where pieces of HTML code are displayed in cases where the `reldateAutoUpdate` filter is used.
- Added the `ng-bind-html` directive where the `reldateAutoUpdate` is used.
_Note: To reproduce this easily, change the date & time in your computer to something in the past (1 hour or 1 day)._
1. Navigate to the Editor's interface.
2. Click "Add content here" and add any content.
3. Click "Live" to see the Live Preview. Click on "Comment" at the top and add a comment.
4. Navigate back to the Editor's interface and go to the comments section.
5. The comment timestamp should show correctly without HTML code.
| Original  | New |
| ------------- | ------------- |
| ![image](https://github.com/liveblog/liveblog/assets/14116447/00bc6874-05f5-4af9-ab3d-3f4a4f228702) | …
> [LBSD-2734] - Comments display a piece of HTML code when viewed in the LB editor

- .github/workflows/continuous-integration.yml
- client/package-lock.json
- server/liveblog/blogs/tasks.py
- server/liveblog/blogs/tests/utils_test.py
- server/liveblog/blogs/utils.py
- server/liveblog/items/items.py
- server/liveblog/items/tests/items_test.py
- server/liveblog/posts/tasks.py
- server/liveblog/themes/themes.py
This the first of two PRs to solve [LBSD-2733]. The second PR will be about giving feedback to client about the failure of generating the embed with the selected theme.
There were a couple of problems that have been fixed in this refactoring. Sometimes the `_publish_blog_embed_on_s3` function was provided without a theme (`None` value) which led to an error while generating the embed. While working on this refactoring I figured out that the theme parameter was really unnecessary therefore it has been removed. Now, to generate the embed, the function would use either the blog's theme or the output channel theme if provided.
The other issue that has been solved is that the `public_url` value of the blog was not being saved after the initial embed generation was processed. If the initial …
> [LBSD-2733] - Refactor `publish_blog_embed_to_s3` task

- server/liveblog/instance_settings/__init__.py
- server/liveblog/instance_settings/instance_settings.py
- server/liveblog/prepopulate/data_init/instance_settings.json
- server/liveblog/validator.py
- server/settings.py
This PR introduces a new database collection to store instance settings in JSON format. The purpose of these changes is to ensure that instance configurations are both flexible and robust, allowing settings to be defined and adjusted during deployment and throughout the lifecycle of the instance. The new settings mechanism includes validation to prevent configurations that could disrupt application functionality.
- New DB Collection: Implemented a collection in the database to store instance settings as JSON. This allows dynamic and flexible configuration management.
- Schema Validation: Added schema validation logic to ensure the integrity of the JSON data, protecting the application from potential misconfiguration.
- Default Configuration Fixture: Introduced a fixture file containing …
> [LBSD-2782] - Implement new backend structure to store Instance Settings

- client/app/scripts/liveblog-edit/module.js
- client/spec/editor_contribution_posts_spec.js
- client/spec/editor_embed_post_spec.js
- client/spec/editor_imageupload_post_spec.js
- client/spec/helpers/pages.js
- client/spec/poll_spec.js
This PR reverts #1368 [LBSD-2774](https://github.com/liveblog/liveblog/pull/1368) reversing the changes made due to the introduction of an editor reorder bug when editing. 
- **Reverting back changes** - Changes made in LBSD-2774 have been reverted
- **Post types don't appear by default** - This reversion results in the default behavior where the "Add Content Here" must be clicked to show post types. A better way to implement this will be done in a subsequent PR.
1. Navigate to the Editor's interface.
2. The block options shouldn't be shown until the user clicks "Add Content Here"
3. Create a new post with multiple items and publish it. 
4. Edit the post and the items should appear in order on the Editor panel.
Resolves: [LBSD-2791](https://sofab.atlassian.net/browse/LBSD-2791) …
> [LBSD-2791] - Reverts #1368

- server/liveblog/prepopulate/app_initialize.py
This PR fixes an issue that was causing a `WiredTigerIndex::insert: key too large to index` issue when running the `initialize_data` command when initializing the instance settings. This is because the settings index was exceeding MongoDB's index size limit. 
- Changed the index param from `settings` to 5 smaller individual plan indexes. 
1. Start the docker service and the backend.
2. Run the command `python3 manage.py app:initialize_data;`. Observe that the command runs with no errors.
Resolves: [LBSD-2814](https://sofab.atlassian.net/browse/LBSD-2814)
[LBSD-2814]: https://sofab.atlassian.net/browse/LBSD-2814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LBSD-2814] - Fix Large Index Key issue when running `initialize_data` command

- client/app/scripts/liveblog-edit/components/itemEmbedFacebook.tsx
- client/app/scripts/liveblog-edit/components/itemEmbedRender.tsx
- client/app/scripts/liveblog-edit/views/main.ng1
- client/package-lock.json
- client/package.json
This PR fixes a bug where the Facebook embeds are not loading on Editor.
- Update the `react-social-media-embed` package.
- Added a new `itemEmbedFacebook` component to load Facebook embeds manually on the Editor. 
1. Open the Editor.
2. Add a new post which is a Facebook embed. Observe that it loads correctly on the timeline.
Resolves: [LBSD-2816](https://sofab.atlassian.net/browse/LBSD-2816)
[LBSD-2816]: https://sofab.atlassian.net/browse/LBSD-2816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LBSD-2816] - Facebook embeds not loading on Editor

- .github/workflows/continuous-integration.yml
- server/liveblog/blogs/blog.py
- server/liveblog/blogs/tests/blog_test.py
There are some cases when the users create a post but do not publish it right away (like scheduled posts). Such posts, could end up not being rendered in the right position when using Newest First or Oldest First tabs in the readers side as it was using `_created` attribute which is assigned at the time the entry is added into the database. To avoid such issues, we need to use `published_date` attribute instead, as this is the one that stores the real date and time when the post is available to the readers
The ordering attribute for the embed generation has been changed from `_created` to `published_date`
- Checkout the branch and run the project
- Create a blog, set default ordering to "Newest First" in Theme Settings section
- Create multiple posts. Add a scheduled one that would end up …
> Change `newest_first` and `oldest_first` ordering attribute

- client/app/scripts/liveblog-edit/styles/liveblog-edit.scss
This PR fixes the issue of Freetypes overlapping each other on the editor
- Added styling to enable word breaks and auto height adjustment for the Freetypes list item.
1. Navigate to the Editor's interface.
2. Click "Choose Post Type". A popup should show with a list of all post type. The list should be scrollable.
| Original  | New |
| ------------- | ------------- |
| ![image](https://github.com/liveblog/liveblog/assets/14116447/4e68ab79-edba-45ac-bb34-f8856b60a5f5) |   ![image](https://github.com/liveblog/liveblog/assets/14116447/72b38774-3518-4b9c-9277-a6dfc9ba62c5) |
Resolves: [LBSD-2800](https://sofab.atlassian.net/browse/LBSD-2800)
[LBSD-2800]: https://sofab.atlassian.net/browse/LBSD-2800?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LBSD-2800] - The list when choosing a list type has UI issues in Firefox

- server/liveblog/instance_settings/features_service.py
This PR fixes an issue where an error is thrown on the Team package when trying to create a 3rd blog which should be possible since its not beyond it's subscription limit.
- Changed the conditional operator to `>` instead of `>=` since the `current_usage` passed in the function is a summation of active blogs plus the number of new blogs to be made.
1. Ensure you set `SUBSCRIPTION_LEVEL='team'` in your .env file
2. Run Liveblog
3. Open the Editor and create 3 blogs. Observer that they will be created.
4. Trying to create a 4th blog will show a modal indicating you cannot create more blogs.
Resolves: [LBSD-2831](https://sofab.atlassian.net/browse/LBSD-2831)
[LBSD-2831]: https://sofab.atlassian.net/browse/LBSD-2831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHVi …
> [LBSD-2831] - Error when creating 3rd blog for Team package

- client/app/scripts/liveblog-themes/module.js
- server/liveblog/blogs/blogs.py
- server/liveblog/themes/tests/theme_settings_test.py
- server/liveblog/themes/themes.py
This PR fixes the `blog_preferences.theme` lookup failure by making use of the `get_from_mongo` function to instead use Mongo and not Elastic. This PR also fixes [LBSD-2861](https://github.com/liveblog/liveblog/pull/1410)
- Changed the blogs `get` api to use `get_from_mongo` if the `where` arg is present in the params. 
- Changed to `get_from_mongo` where `blog_preferences.theme` is used in the codebase.
- Changed the criteria on the front end to use the where keyword for theme count filtration.
1. Open the Editor
2. Create several blogs with several themes.
3. Open the side menu and head to the "Theme Manager".
4. Observe that for each theme, the number of blogs using the theme is accurate.
Resolves: [LBSD-2863](https://sofab.atlassian.net/browse/LBSD-2863)
[LBSD-2861]: …
> [LBSD-2863] - Investigate `blog_preferences.theme` lookup 

- server/liveblog/client_modules/client_modules.py
Refactor ClientPollsService to override etag change from patch update to use the previous etag
- Added `update` function to ClientPollsService to handle poll update and etag consistency
- Added necessary documentation
1. Open the Editor and publish a new poll.
2. Open the preview and place a vote.
3. Observe that the request to fetch a poll first to get the etag has the same etag as the response from the patch request
Resolves: [LBSD-2879](https://sofab.atlassian.net/browse/LBSD-2879)
[LBSD-2879]: https://sofab.atlassian.net/browse/LBSD-2879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LBSD-2879] - Refactor clientpolls to handle etag consistency

- client/app/scripts/liveblog-edit/blog.service.js
- server/liveblog/blogs/tasks.py
- server/liveblog/themes/themes_assets/amp/package.json
- server/liveblog/themes/themes_assets/amp/theme.json
- server/liveblog/themes/themes_assets/simple/package.json
- server/liveblog/themes/themes_assets/simple/theme.json
This PR adds a fallback mechanism to revert back to default theme if an embed generation fails on any other blog theme generation.
- Added fallback mechanism for blog embed generation to default theme.
- Updated Simple and AMP theme to use latest dev version of default theme.
The easiest way to test this would be to mock an exception in the embed generation function. Just throw the exception after line 47 in the code below, restart your services and then update the blog theme. Observe the notification on the UI. Also observe that on refresh the theme is set as the Default theme.
https://github.com/liveblog/liveblog/blob/987a234d2da572a5775c1d8a68897ec483ebf75a/server/liveblog/blogs/tasks.py#L46-L57
Resolves: [LBSD-2876](https://sofab.atlassian.net/browse/LBSD-2876)
[LBSD-2876]: …
> [LBSD-2876] - After switching to child theme and getting error, going back to Default theme is not possible

- client/app/scripts/liveblog-settings/controllers/general-settings.ts
- client/app/scripts/liveblog-settings/controllers/instance-settings.ts
Fix broken references to removed method from notification module.
We should double check all usages of `notify` module across the app to see if the little messages are showing/hiding properly
> Remove usages of `notify.pop` as it no longer exists

- client/app/scripts/liveblog-edit/posts.service.ts
- server/liveblog/posts/posts.py
This PR resolve an error that occurs when deleting comments on the Editor panel.
- Added a check when updating comments where if the `deleted: True` it skips getting the blog_id from the item as well as checking the comment length.
1. Open Editor. Create a blog and publish a post. 
2. Go to the Live preview and add a comment.
3. Navigate back to the Editor and open the Comments panel and delete the comment.
4. Observe that the comment is deleted without an errors.
Resolves: [LBSD-2903](https://sofab.atlassian.net/browse/LBSD-2903)
[LBSD-2903]: https://sofab.atlassian.net/browse/LBSD-2903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LBSD-2903] - Resolve error when deleting comments before publishing

- server/liveblog/blogposting_schema/utils.py
To remove the html tags from the schema's article body. At the moment html tags are being rendered and according to the specification, the articleBody should be plain text. 
- Added a small util function to remove the html tags but preserve line breaks (replace `<br>` tags with `\n`)
- Create a blog with a few posts
- Go to the embed view
- Observe in the `LiveBlogPosting > liveBlogUpdate` that the attribute `articleBody` does not contain html tags
Thanks for checking!
Resolves: [LBSD-2909]
[LBSD-2909]: https://sofab.atlassian.net/browse/LBSD-2909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [LBSD-2909] Strip html tags from LiveblogPostingSchema's `articleBody`
